# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ayuda.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ayuda(object):
    def setupUi(self, Ayuda):
        Ayuda.setObjectName("Ayuda")
        Ayuda.resize(400, 200)
        Ayuda.setMinimumSize(QtCore.QSize(400, 200))
        Ayuda.setMaximumSize(QtCore.QSize(400, 200))
        self.label_Logo = QtWidgets.QLabel(Ayuda)
        self.label_Logo.setGeometry(QtCore.QRect(20, 40, 91, 91))
        self.label_Logo.setStyleSheet("image: url(:/Logo/PNG/Logo.png);")
        self.label_Logo.setText("")
        self.label_Logo.setObjectName("label_Logo")
        self.label_Titulo = QtWidgets.QLabel(Ayuda)
        self.label_Titulo.setGeometry(QtCore.QRect(130, 20, 251, 21))
        self.label_Titulo.setStyleSheet("font: 85 11pt \"Arial Black\";")
        self.label_Titulo.setObjectName("label_Titulo")
        self.label_Descripcion = QtWidgets.QLabel(Ayuda)
        self.label_Descripcion.setGeometry(QtCore.QRect(130, 50, 260, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Descripcion.setFont(font)
        self.label_Descripcion.setStyleSheet("font: 8pt \"Arial\";")
        self.label_Descripcion.setObjectName("label_Descripcion")
        self.pushButton_Cerrar = QtWidgets.QPushButton(Ayuda)
        self.pushButton_Cerrar.setGeometry(QtCore.QRect(300, 160, 80, 25))
        self.pushButton_Cerrar.setObjectName("pushButton_Cerrar")

        self.retranslateUi(Ayuda)
        self.pushButton_Cerrar.clicked.connect(Ayuda.close)
        QtCore.QMetaObject.connectSlotsByName(Ayuda)

    def retranslateUi(self, Ayuda):
        _translate = QtCore.QCoreApplication.translate
        Ayuda.setWindowTitle(_translate("Ayuda", "Ayuda"))
        self.label_Titulo.setText(_translate("Ayuda", "Cohemo GMP"))
        self.label_Descripcion.setText(_translate("Ayuda", "Version 1.0\n"
"Cohemo GMP es un generador de informes \n"
"PDF de ensayos de grupos motopropulsores.\n"
"\n"
"Copyright (C) 2021 Cohemo SL."))
        self.pushButton_Cerrar.setText(_translate("Ayuda", "Cerrar"))

import Recursos.Python.Logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ayuda = QtWidgets.QDialog()
    ui = Ui_Ayuda()
    ui.setupUi(Ayuda)
    Ayuda.show()
    sys.exit(app.exec_())
